-- MySQL Script generated by MySQL Workbench
-- Wed May  4 13:19:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

USE CollegeDepartmentDB;
SET SQL_SAFE_UPDATES = 0;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CollegeDepartmentDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CollegeDepartmentDB`;
-- -----------------------------------------------------
-- Schema CollegeDepartmentDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CollegeDepartmentDB` DEFAULT CHARACTER SET utf8 ;
USE `CollegeDepartmentDB` ;

-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`University`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`University` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`University` (
  `u_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `founding_year` INT NOT NULL,
  `num_students` INT NOT NULL,
  PRIMARY KEY (`u_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`Student` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`Student` (
  `student_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `dob` DATE NOT NULL,
  `student_email` VARCHAR(45) NULL,
  PRIMARY KEY (`student_id`),
  UNIQUE INDEX `student_email_UNIQUE` (`student_email` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`Instructor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`Instructor` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`Instructor` (
  `instructor_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `num_courses` INT NOT NULL,
  `years_teaching` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`instructor_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`FacultyMember`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`FacultyMember` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`FacultyMember` (
  `faculty_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `salary` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`faculty_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`Department` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`Department` (
  `department_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `num_instructors` INT NOT NULL,
  `budget` INT NOT NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`Major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`Major` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`Major` (
  `major_id` INT NOT NULL,
  `num_students` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`major_id`, `department_id`),
  INDEX `department_id_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `department_id`
    FOREIGN KEY (`department_id`)
    REFERENCES `CollegeDepartmentDB`.`Department` (`department_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`Course` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`Course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `num_classes` INT NOT NULL,
  `prerequisites` VARCHAR(45) NULL,
  `title` VARCHAR(45) NOT NULL,
  `units` INT NOT NULL,
  `major_id` INT NOT NULL,
  PRIMARY KEY (`course_id`, `units`, `major_id`),
  INDEX `major_name_idx` (`major_id` ASC) VISIBLE,
  CONSTRAINT `major_id`
    FOREIGN KEY (`major_id`)
    REFERENCES `CollegeDepartmentDB`.`Major` (`major_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`Class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`Class` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`Class` (
  `section_id` INT NOT NULL AUTO_INCREMENT,
  `semester` VARCHAR(45) NOT NULL,
  `num_add_codes` INT NOT NULL,
  `instructor_name` VARCHAR(45) NOT NULL,
  `grade` CHAR(3) NULL,
  PRIMARY KEY (`section_id`, `num_add_codes`, `instructor_name`),
  INDEX `instructor_name_idx` (`instructor_name` ASC) VISIBLE,
  CONSTRAINT `instructor_name`
    FOREIGN KEY (`instructor_name`)
    REFERENCES `CollegeDepartmentDB`.`Instructor` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`PaymentMethod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`PaymentMethod` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`PaymentMethod` (
  `pm_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pm_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`Account` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`Account` (
  `account_id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `pm_id` INT NULL,
  PRIMARY KEY (`account_id`, `email`),
  INDEX `pm_id_idx` (`pm_id` ASC) VISIBLE,
  INDEX `email_idx` (`email` ASC) VISIBLE,
  CONSTRAINT `pm_id`
    FOREIGN KEY (`pm_id`)
    REFERENCES `CollegeDepartmentDB`.`PaymentMethod` (`pm_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`AddCode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`AddCode` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`AddCode` (
  `code_id` INT NOT NULL AUTO_INCREMENT,
  `section` INT NOT NULL,
  `expiration_date` DATE NOT NULL,
  PRIMARY KEY (`code_id`),
  INDEX `class_section_idx` (`section` ASC) VISIBLE,
  CONSTRAINT `class_section`
    FOREIGN KEY (`section`)
    REFERENCES `CollegeDepartmentDB`.`Class` (`section_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`Researcher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`Researcher` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`Researcher` (
  `r_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `field_of_research` VARCHAR(45) NOT NULL,
  `r_grant` INT NOT NULL,
  PRIMARY KEY (`r_id`, `name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`Paper`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`Paper` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`Paper` (
  `paper_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `conference` VARCHAR(45) NULL,
  `publish_date` DATE NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`paper_id`, `author`),
  INDEX `author_name_idx` (`author` ASC) VISIBLE,
  UNIQUE INDEX `author_UNIQUE` (`author` ASC) VISIBLE,
  CONSTRAINT `author_name`
    FOREIGN KEY (`author`)
    REFERENCES `CollegeDepartmentDB`.`Researcher` (`name`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`Administrator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`Administrator` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`Administrator` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `salary` INT NOT NULL,
  `uni_id` INT NOT NULL,
  PRIMARY KEY (`admin_id`),
  INDEX `uni_id_idx` (`uni_id` ASC) VISIBLE,
  CONSTRAINT `uni_id`
    FOREIGN KEY (`uni_id`)
    REFERENCES `CollegeDepartmentDB`.`University` (`u_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`Transcript`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`Transcript` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`Transcript` (
  `transcript_id` INT NOT NULL,
  `num_courses` INT NOT NULL,
  `student_name` VARCHAR(45) NOT NULL,
  `gpa` DECIMAL(2,1) NOT NULL,
  PRIMARY KEY (`transcript_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`CreditCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`CreditCard` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`CreditCard` (
  `card_id` INT NOT NULL,
  `expiration_date` DATE NOT NULL,
  `name_on_card` VARCHAR(45) NOT NULL,
  `card_number` INT NOT NULL,
  `pm_id` INT NOT NULL,
  PRIMARY KEY (`card_id`, `pm_id`),
  INDEX `pm_id_idx` (`pm_id` ASC) VISIBLE,
  CONSTRAINT `pm_id_card`
    FOREIGN KEY (`pm_id`)
    REFERENCES `CollegeDepartmentDB`.`PaymentMethod` (`pm_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`Check`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`Check` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`Check` (
  `check_id` INT NOT NULL,
  `pm_id` INT NOT NULL,
  `routing_number` INT NOT NULL,
  PRIMARY KEY (`check_id`, `pm_id`),
  INDEX `pm_id_idx` (`pm_id` ASC) VISIBLE,
  CONSTRAINT `pm`
    FOREIGN KEY (`pm_id`)
    REFERENCES `CollegeDepartmentDB`.`PaymentMethod` (`pm_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`Chancellor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`Chancellor` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`Chancellor` (
  `chancellor_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `years_held_position` INT NOT NULL,
  PRIMARY KEY (`chancellor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`Grader`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`Grader` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`Grader` (
  `grader_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `instructor` VARCHAR(45) NOT NULL,
  `salary` INT NOT NULL,
  PRIMARY KEY (`grader_id`),
  INDEX `instructor_name_idx` (`instructor` ASC) VISIBLE,
  CONSTRAINT `i_name_g`
    FOREIGN KEY (`instructor`)
    REFERENCES `CollegeDepartmentDB`.`Instructor` (`name`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`ClassesTaught`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`ClassesTaught` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`ClassesTaught` (
  `c_id` INT NOT NULL,
  `i_id` INT NOT NULL,
  PRIMARY KEY (`c_id`, `i_id`),
  INDEX `i_id_idx` (`i_id` ASC) VISIBLE,
  CONSTRAINT `i_id_ct`
    FOREIGN KEY (`i_id`)
    REFERENCES `CollegeDepartmentDB`.`Instructor` (`instructor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`Enrollment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`Enrollment` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`Enrollment` (
  `c_id` INT NOT NULL,
  `s_id` INT NOT NULL,
  PRIMARY KEY (`c_id`, `s_id`),
  INDEX `s_id_idx` (`s_id` ASC) VISIBLE,
  CONSTRAINT `s_id`
    FOREIGN KEY (`s_id`)
    REFERENCES `CollegeDepartmentDB`.`Student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`ProcessTranscript`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`ProcessTranscript` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`ProcessTranscript` (
  `t_id` INT NOT NULL,
  `s_id` INT NOT NULL,
  PRIMARY KEY (`t_id`, `s_id`),
  INDEX `s_id_idx` (`s_id` ASC) VISIBLE,
  CONSTRAINT `s_id_pt`
    FOREIGN KEY (`s_id`)
    REFERENCES `CollegeDepartmentDB`.`Student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`BillingInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`BillingInfo` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`BillingInfo` (
  `billing_id` TINYINT(1) NOT NULL,
  `account` INT NOT NULL,
  `payment_type` VARCHAR(45) NOT NULL,
  `amount` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`billing_id`),
  INDEX `account_idx` (`account` ASC) VISIBLE,
  CONSTRAINT `account_b`
    FOREIGN KEY (`account`)
    REFERENCES `CollegeDepartmentDB`.`Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`AddFaculty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`AddFaculty` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`AddFaculty` (
  `d_id` INT NOT NULL,
  `f_id` INT NOT NULL,
  PRIMARY KEY (`d_id`, `f_id`),
  INDEX `faculty_idx` (`f_id` ASC) VISIBLE,
  CONSTRAINT `department_af`
    FOREIGN KEY (`d_id`)
    REFERENCES `CollegeDepartmentDB`.`Department` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `faculty_af`
    FOREIGN KEY (`f_id`)
    REFERENCES `CollegeDepartmentDB`.`FacultyMember` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`AddCodeStudent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`AddCodeStudent` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`AddCodeStudent` (
  `c_id` INT NOT NULL,
  `s_id` INT NOT NULL,
  PRIMARY KEY (`c_id`, `s_id`),
  INDEX `student_idx` (`s_id` ASC) VISIBLE,
  CONSTRAINT `code`
    FOREIGN KEY (`c_id`)
    REFERENCES `CollegeDepartmentDB`.`AddCode` (`code_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `student`
    FOREIGN KEY (`s_id`)
    REFERENCES `CollegeDepartmentDB`.`Student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`Publish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`Publish` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`Publish` (
  `p_id` INT NOT NULL,
  `r_id` INT NOT NULL,
  PRIMARY KEY (`p_id`, `r_id`),
  INDEX `researcher_idx` (`r_id` ASC) VISIBLE,
  CONSTRAINT `researcher`
    FOREIGN KEY (`r_id`)
    REFERENCES `CollegeDepartmentDB`.`Researcher` (`r_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`LinkDepartment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`LinkDepartment` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`LinkDepartment` (
  `u_id` INT NOT NULL,
  `d_id` INT NOT NULL,
  PRIMARY KEY (`u_id`, `d_id`),
  CONSTRAINT `university`
    FOREIGN KEY (`u_id`)
    REFERENCES `CollegeDepartmentDB`.`University` (`u_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`StudentAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`StudentAccount` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`StudentAccount` (
  `s_id` INT NOT NULL,
  `a_id` INT NOT NULL,
  PRIMARY KEY (`s_id`, `a_id`),
  INDEX `account_idx` (`a_id` ASC) VISIBLE,
  CONSTRAINT `account_sa`
    FOREIGN KEY (`a_id`)
    REFERENCES `CollegeDepartmentDB`.`Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`FacultyAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`FacultyAccount` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`FacultyAccount` (
  `f_id` INT NOT NULL,
  `a_id` INT NOT NULL,
  PRIMARY KEY (`f_id`, `a_id`),
  INDEX `account_idx` (`a_id` ASC) VISIBLE,
  CONSTRAINT `account_fa`
    FOREIGN KEY (`a_id`)
    REFERENCES `CollegeDepartmentDB`.`Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`CourseClass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`CourseClass` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`CourseClass` (
  `co_id` INT NOT NULL,
  `cl_id` INT NOT NULL,
  PRIMARY KEY (`co_id`, `cl_id`),
  INDEX `class_idx` (`cl_id` ASC) VISIBLE,
  CONSTRAINT `course`
    FOREIGN KEY (`co_id`)
    REFERENCES `CollegeDepartmentDB`.`Course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `class`
    FOREIGN KEY (`cl_id`)
    REFERENCES `CollegeDepartmentDB`.`Class` (`section_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeDepartmentDB`.`InstructorCourse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CollegeDepartmentDB`.`InstructorCourse` ;

CREATE TABLE IF NOT EXISTS `CollegeDepartmentDB`.`InstructorCourse` (
  `i_id` INT NOT NULL,
  `c_id` INT NOT NULL,
  PRIMARY KEY (`i_id`, `c_id`),
  INDEX `course_idx` (`c_id` ASC) VISIBLE,
  CONSTRAINT `instructor_ic`
    FOREIGN KEY (`i_id`)
    REFERENCES `CollegeDepartmentDB`.`Instructor` (`instructor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `course_ic`
    FOREIGN KEY (`c_id`)
    REFERENCES `CollegeDepartmentDB`.`Course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
